// Irregular word mappings
const Map<String, String> irregularPlurals = {
  'child': 'children',
  'person': 'people',
  'mouse': 'mice',
  'foot': 'feet',
  'tooth': 'teeth',
  'goose': 'geese',
  'man': 'men',
  'woman': 'women',
  'ox': 'oxen',
  'cactus': 'cacti',
  'fungus': 'fungi',
  'nucleus': 'nuclei',
  'focus': 'foci',
  'virus': 'viruses',
  'alumnus': 'alumni',
  'criterion': 'criteria',
  'phenomenon': 'phenomena',
  'appendix': 'appendices',
  'matrix': 'matrices',
  'datum': 'data',
  'medium': 'media',
  'bacterium': 'bacteria',
  'analysis': 'analyses',
  'thesis': 'theses',
  'diagnosis': 'diagnoses',
  'hypothesis': 'hypotheses',
  'atlas': 'atlases',
  'axis': 'axes',
  // Add more irregular words if needed
};
